server:
  port: 8090
grpc:
  server:
    port: 9091
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    export:
      atlas:
        enabled: false
  security:
    enabled: false

spring:
  application:
    name: svc-rps-support-session
  data:
    mongo-database:
      host: localhost
      port: 27017
      auto-index-creation: true
  cloud:
    function:
      definition: stringSupplier;toUpperCase;stringLogger
    stream:
      poller:
        fixed-delay: 10000
      bindings:
        stringSupplier-out-0:
          destination: strings-topic
          binder: nats
        toUpperCase-in-0:
          destination: strings-topic
          binder: nats
        stringLogger-in-0:
          destination: logger-topic
          binder: nats
        toUpperCase-out-0:
          destination: logger-topic
          binder: nats

nats:
  spring:
    server: nats://localhost:4222

logging:
  level:
    org.springframework: ERROR
    com.sessionManager.sessionManager: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

#opentracing:
#  jaeger:
#    service-name: svc-rps-support-session
#    enabled: TRUE
#    udp-sender:
#      host: jaeger
#    http-sender:
#      url: http://localhost:14268/api/traces